### ISSUE TITLE
Any Pointers for Exercise 2.4?

### ISSUE THREAD

**Issue by T-Spoon** [mightybyte/monad-challenges#34]
I have a couple of general Haskell questions relating to problem 2.4:

1) How can I get `link` to work with `divMay` i.e. because divMay takes two arguments, I can't just pass the function in normally.  Is there some Haskell trick I can use to bypass this?

2) `fromIntegral` has the signature `a -> b`, but in my current setup I need `Maybe a -> b`.  And without case expressions I'm not sure how to go about doing this.

My current work in progress looks like this:

```
queryGreek2 :: GreekData -> String -> Maybe Double
queryGreek2 dat q = divMay mx h
    where
        res = lookupMay q dat
        t   = link res tailMay
        h   = link res headMay
        mx  = link t maximumMay
        mxi = link mx fromIntegral
        hi  = link h fromIntegral
```

I'm sure it would make an experienced Haskell programmer's eyes bleed!  And obviously this doesn't work, due to the issues mentioned above.

Any tips would be much appreciated!

**Comment by spearsem** [comment]
I chose to write an additional helper function called `fromIntegralMay` which is very similar to the other functions like `headMay` and so on. I figured this is perfectly valid since we're already doing that with other functions, and if we would go to the trouble of making something like `link` that can "thread" Maybe-returning functions through a sequence, it doesn't make sense to artificially still require the use of a function that doesn't follow that format (like the way that plain `fromIntegral` doesn't). I may have been incorrect in this choice, but it allowed me to write the function using only `link` compositions, which I believe is the point of it.

For your first question, this is where you need to use a kludgy-feeling lambda function. You're exactly correct that you can't thread one argument at a time through the two-argument `divMay` function. So you need some way of currying the first argument onto `divMay`, and once it is curried, the resulting thing will have the same old `a -> Maybe b` type signature that is easily `link`-able.

So the trick of it is, if you start with the first argument to `divMay`, what is a lambda function that you _could_ `link` it through, such that you can further `link` the other argument inside the lambda?

I'm sure there are other ways to do it too, but that was the way that it made some sense to me.

**Comment by T-Spoon** [comment]
@spearsem Thanks for the advice!  I had actually tried the `fromIntegralMay`, but ran into the problem described below, so I thought I was on the wrong track.

My code currently looks like this:

```
fromIntegralMay :: (Integral a, Num b) => a -> Maybe b
fromIntegralMay a    = Just (fromIntegral a)

queryGreek2 :: GreekData -> String -> Maybe Double
queryGreek2 dat q =
    let f = (\ a -> divMay a)
    in link hi (f mxi)
    where
        res = lookupMay q dat
        t   = link res tailMay
        h   = link res headMay
        mx  = link t maximumMay
        mxi = link mx fromIntegralMay
        hi  = link h fromIntegralMay
```

My problem is that in order to apply `mxi` to `f`, it can't be of the `Maybe` type.  And I'm not sure how I can cast it without using case/if-then-else expressions.  Or create a new function that pattern matches (which is basically the same thing as far as I can see(?) ).

I could write `(Just mxi) = link mx fromIntegralMay`, but then of course that fails when `mx` is `Nothing`.  But the signature for `fromIntegralMay` can't accept a `Maybe a` anyway (if it's to work with `link`). So it seems like the chain breaks down there.

Any idea what I'm missing here?

**Comment by mightybyte** [comment]
@T-Spoon As you've observed, `link` is not quite the right abstraction for divMay.  But you actually don't need anything special here because divMay is at the end of the chain of calls and you should already have pure non-maybe values for the things that you have to pass into divMay.  Since the result of queryGreek2 is a Maybe and the result of divMay is a Maybe, it all works out.  You also shouldn't need a fromIntegralMay function.  What you want to do is capture names for things as you go along by using lambdas.  I don't want to give any code here because that will give too much away, but if you're still stuck you can email me at my username at gmail and I'll give you a bigger hint.

**Comment by spearsem** [comment]
@T-Spoon In your last bit of code, you're extremely close. The final issue is with the way you apply the helper function `f` to `mxi`. Note that `mxi` comes from the use of `link` with a safe function. So `mxi` will be a `Maybe` type. How do you feed `Maybe` types into functions that accept pure types?

@mightybyte I did not solve the problem in a manner that resembles what you are saying. My solution is 3 lines of code with only a single lambda, and uses `link` for everything. Your explanation of using lots of lambdas like they are closures for names actually confuses me quite a bit. Just from re-reading the exercise, I don't understand that and I think it would be particularly difficult to get any help unless I was able to share my full solution code with you and try to understand why it is not the "right" way of composing things with `link`.

Do you think there's any way we could set up a feedback arena like that? Maybe by opening a new issue called "spoilers" that people won't view unless they have to?

**Comment by mightybyte** [comment]
@spearsem Hmmm, I'd love to see your solution.  Feel free to email it to me.  I don't think there's necessarily a "right" way.  The way that I had in mind (if that's what you mean by "right") is the one that roughly corresponds to how do notation gets desugared.

Setting up a feedback arena sounds like a cool idea to me.  I'm not quite sure of the best way to go about that.  I'm concerned that such a thing would significantly reduce the incentive for readers to spend significant time playing around with different approaches and in general puzzling things out.  But I do recognize that there are situations where you're just stuck and you need outside help to move forward.  I think maybe a feedback arena like you're talking about would be most helpful in this early period while the challenges are still rough and need a lot of work.  I would hope that after the challenges have been around awhile and get really polished a feedback arena would not even be necessary.  But maybe that's just wishful thinking.

**Comment by T-Spoon** [comment]
@spearsem To feed a  `Maybe` type to a function that accepts pure types, I would use `link` But in this case I don't see how I can do that - since that would return another `Maybe` (instead of the function I need it to return). Any chance you'd be able to send me your solution via email, so I can say "Ahhh", then bang my head against the table for missing it. My email is gtspoon _ hotmail _ com

@mightybyte I sent you an email too - since I'd like to understand both solutions eventually. 

I think a feedback arena would be great - maybe an issue type of "Spoiler" for each exercise? Or even some extra hints (like in 1.3) could help.
