### ISSUE TITLE
Set 3 is about Combinations not Permutations

### ISSUE THREAD

**Issue by hansroland** [mightybyte/monad-challenges#40]
Thinking about the problem in 3.5  (Permutations of more things) I realized, that the topic of Set 3 are Combinations and not Permutations.

A Permutation is a rearrangement of the elements of a list. [See Wikipedia](https://en.wikipedia.org/wiki/Permutation)
But in these exercises, we have to create all combinations of the elements of 2, 3 or many sets.
Mathematically spoken, we have to build the Cartesian Product of the input sets.

The type signature of a function _allPerms_ would be

`allPerms :: [a] -> [[a]]`

The text should be changed and the function of Set 3.3 should be called something like "allCombinations\* or *allCombs.

PS: monad-challenges is a great tutorial !!

**Comment by mightybyte** [comment]
Ahh yes, I fixed it.  Thanks!

**Comment by spearsem** [comment]
I think the term "combination" is totally fine for this exercise and I am not suggesting that we need to change it again. 

However, if we wanted to be mathematically pedantic, exercise 3 is about the Cartesian product, not about combinations nor permutations. Maybe it would be good to add just a quick note about it? Something like "We will use the term 'combination' to mean an element from the Cartesian product."

This could also be a good opportunity to highlight the power of functional abstractions. If you try to implement the Cartesian product algorithm in an imperative language, you have do nested loops, or else you have to do an "odometer" algorithm, where you keep track of how many elements you've consumed from each sequence, and when you reach the end, you "trip" the next "digit" in the counter. It's not a particularly pretty algorithm.

**Comment by mightybyte** [comment]
Good point.  If you want to take a stab at a more correct rewording that points this out more explicitly, feel free.  I'm very open to accepting such a change.

**Comment by spearsem** [comment]
I definitely plan to work on some that ... please don't interpret anything I am saying as if it's placing a demand on you for it. 

I tend to be pedantic about documenting things in issues rather than just jumping in with pull request changes, but I plan to get to it soon.

You've done an awful lot of excellent work here, and the last thing I want is for you to feel like we're pressuring you over minor changes like this. For one, you don't owe anyone all this effort, and for two, we are perfectly capable to generate pull requests for a lot of this stuff.

**Comment by mightybyte** [comment]
Great, thanks.  I don't feel pressured.  I do like to be completely technically correct with the things I write, so I really appreciate your point here.
