### ISSUE TITLE
Odd order of sentences in exercise 2.3

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#6]
In exercise 2.3, it says

> Next calculate the maximum of the tail of xs. (Don’t use any pattern matching here. Use the headMay and tailMay functions you wrote in the last exercise.)

This confused me - why would I want to use `headMay` or pattern matching here? It seems I just need `tailMay` and `maximumMay`. However, the text goes on:

> Take the maximum and divide it by the head of the list (using your divMay function).

Aha, now at least there's a reason to use `headMay`. Still, this section is quite rough - and no mentioning of `maximumMay`.

**Comment by spearsem** [comment]
This section continues to confuse me. Shouldn't case statements also count as pattern matching? 

I might be missing something critical to the exercise, but I do not understand the wording of this because it makes it sound as if, using only `headMay` and the other functions, there is a way we can automatically sequence the computations without directly referring to whether or not a computation results in `Nothing`. 

But I think that's wrong. If we could already do that without cases / pattern matching, we would already have all of the monad-like threading capabilities that the exercise is slowly having us build.

Can anyone help clarify this? I don't want to write the naive solution that I think is correct because it uses cases. But because the problem says "don't use any pattern matching" I can only assume that all use of case statements is also disallowed. If so, then I am missing a major concept of this problem and some hint would be necessary.

**Comment by mlsteele** [comment]
I found the wording about not using pattern matching confusing as well

Maybe something like this?
"Don’t use pattern matching here. Use the headMay and tailMay functions you wrote in the last exercise together with case statements."

@spearsem It seems like `case` expressions are the intended way to solve this challenge. The next challenge starts with "If you solved the last challenge correctly, your function has no fewer than three case expressions."

**Comment by mightybyte** [comment]
Ok, I have tweaked the wording a little bit.  Does the new wording clarify things for you?  The reason I say to use case expressions is because I think it drives home the pain a little more and avoids the possibility that the reader might use incomplete pattern matches and think that it's possible to have a much simpler solution.  If you still think it's unclear, please feel free to reopen this issue.

**Comment by mlsteele** [comment]
Great! I think that's more clear.
