### ISSUE TITLE
Finish set 5

### ISSUE THREAD

**Issue by Xodarap** [mightybyte/monad-challenges#68]
Set 5 is incomplete, and I'm trying to figure out what the best way to implement it is. The instructions currently state: "This set not written yet. Bottom line: go back through sets 1-3 again this time using do notation".

My thought is:

1. Add `fail` to `Monad`, and implement it. This exposes the issues with `fail`: `Gen` in particular doesn't have an obvious `fail` instance. Should we just tell people to plug in `fail s = errorWithoutStackTrace s`?
2. After we have failure figured out, have people go back and do the core methods of set 1-3 using `do` syntax, but not the helper functions. (E.g. they would implement `fiveRand` but not `generalA`.) I would explicitly list out the functions they should implement to avoid confusion.

Does that sound good?

**Comment by mightybyte** [comment]
My goal would be to avoid dealing with `fail` as much as possible.  So yeah...pretty much any reasonable shim would be fine with me.

Ahh yes, that's a good point.  I guess this is where it might help to do more thinking about how this tutorial relates to `Functor` and `Applicative`.  When I set out writing the monad challenges I really wanted to focus on `Monad`, and my attitude was that `Functor` is simple enough that I didn't need to include it, but also that `Applicative` was a more difficult abstraction than I wanted to include.  (This is mainly derived from the memory that Applicative seemed harder to me when I was learning.)

I really don't know what the right answer is here.  My main goal is to tackle head-on the things that are most useful in real world development.  In my experience Monad is used a lot more often, so that's what I tackled.  I'm not sure the fact that one abstraction is a specialization of another one implies that it should be taught before or after.  But I could be convinced otherwise if someone presented a really clear approach that introduces Applicative first.

One thought that I had when I started this was to provide a platform to really demonstrate that all the functionality can be built from just return and bind.  So I think it would be useful to actually have the student implement all the helper functions again.  But this time, give them the real names that those functions have in the standard library.  After all...the overarching point is to get people productive.  One thing that's slightly concerning is that if we tell in later problem sets what standard library functions our odd names actually correspond to, we make it easier for people to cheat.  But of course we ultimately can't prevent people from cheating on this, so it's probably fine to simply provide it in hex encoded format to make it hard to accidentally find the answers.

**Comment by Xodarap** [comment]
Yeah, starting with `Functor` may or may not be the optimal solution, but I don't have the time to do that big of a rewrite in any case. In the case of my team at least, they have already encountered Functor/applicative/monad through Haskell from first principles/learn you a Haskell and are just using these challenges as more practice understanding monads.

I will try to spend some time working on it this week and open up a PR to see what you think.
